#define MODEL_Root              0x28
#define MODEL_Flora             0x27
#define MODEL_CubeModel         0x26
#define MODEL_Landmarks         0x25
#define MODEL_SmallPond5        0x24
#define MODEL_SmallPond4        0x23
#define MODEL_SmallPond3        0x22
#define MODEL_SmallPond2        0x21
#define MODEL_SmallPond1        0x20
#define MODEL_CentralPond       0x1F
#define MODEL_Bookstand         0x1E
#define MODEL_Statue            0x1D
#define MODEL_SunlightCrack6    0x1C
#define MODEL_SunlightCrack5    0x1B
#define MODEL_SunlightCrack4    0x1A
#define MODEL_SunlightCrack3    0x19
#define MODEL_SunlightCrack2    0x18
#define MODEL_SunlightCrack1    0x17
#define MODEL_RandomHomes       0x16
#define MODEL_RandHomeBase2     0x15
#define MODEL_RandHomeBase1     0x14
#define MODEL_ElderHouse        0x13
#define MODEL_ElderHouseBase    0x12
#define MODEL_Orphanage         0x11
#define MODEL_OrphanageBase     0x10
#define MODEL_BVHouse           0xF
#define MODEL_BVHouseBase       0xE
#define MODEL_TPHouse           0xD
#define MODEL_TPHouseBase       0xC
#define MODEL_EntriesAndExits   0xB
#define MODEL_PlaceholderEastExitHole 0xA
#define MODEL_PlaceholderWestExitHole 0x9
#define MODEL_SouthEntrySides   0x8
#define MODEL_SouthEntryFloor   0x7
#define MODEL_Walls             0x6
#define MODEL_EastWall          0x5
#define MODEL_WestWall          0x4
#define MODEL_NorthWall         0x3
#define MODEL_Floor             0x2
#define MODEL_Staircase         0x1
#define MODEL_Floor             0x0

